### ISSUE TITLE
Remove the RubberDuck Add-In, if it is not needed...

### ISSUE THREAD

**Issue by Vitosh** [rubberduck-vba/Battleship#10]
😃 

![capture](https://user-images.githubusercontent.com/4303858/45149428-cb2bfa80-b1c9-11e8-8aa9-01be83568135.PNG)

**Comment by retailcoder** [comment]
Yeah I noticed I had left the early-bound reference in there, to get intellisense on the AssertClass members when writing unit tests, and forgot to remove it.

I edited the "release" to late-bind the Rubberduck type library; I'll late-bind it in the source code too next time I push commits here - or I'll be happy to take a PR that does it, too!
