### ISSUE TITLE
Excel2013+ bug high CPU load if Freeze Panes line is zoomed out of sight

### ISSUE THREAD

**Issue by VolkerConsult** [rubberduck-vba/Battleship#21]
Excel 2013+ seems to have a bug such that if you Freeze Panes and zoom in so that the freeze line is out of sight it starts to recalculate the worksheet's display constantly thereby causing high CPU load.  In order to limit the scroll area and keep the battle fields on display use the worksheet property ScrollArea and limit to $A$1:$AF$32 as in the attachment.
[Excel2013up-bug_frozenPanesOutOfSight.xlsx](https://github.com/rubberduck-vba/Battleship/files/3229740/Excel2013up-bug_frozenPanesOutOfSight.xlsx)

**Comment by retailcoder** [comment]
Fixed!
